<?php

acf_add_local_field_group([
  'key' => 'group_6327ca32092a0',
  'title' => 'Catalogo',
  'fields' => [
    [
      'key' => 'field_6327ca3ad2712',
      'label' => 'Hero',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'placement' => 'top',
      'endpoint' => 0,
    ],
    [
      'key' => 'field_6332394c08a53',
      'label' => 'Primeiro Background da Esquerda',
      'name' => '',
      'type' => 'message',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'message' => 'Abaixo você deverá colocar informações sobre o primeiro background que fica na esquerda.',
      'new_lines' => 'wpautop',
      'esc_html' => 0,
    ],
    [
      'key' => 'field_6327caa3d2714',
      'label' => 'Imagem',
      'name' => 'hero_image_01',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '100',
        'class' => '',
        'id' => '',
      ],
      'return_format' => 'url',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ],
    [
      'key' => 'field_6327caf5d2715',
      'label' => 'Post-it',
      'name' => '',
      'type' => 'message',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '100',
        'class' => '',
        'id' => '',
      ],
      'message' => '',
      'new_lines' => 'wpautop',
      'esc_html' => 0,
    ],
    [
      'key' => 'field_6327cb1fd2716',
      'label' => 'Título',
      'name' => 'hero_01_postit_title',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '33.33',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_6327cb39d2717',
      'label' => 'Subtítulo',
      'name' => 'hero_01_postit_subtitle',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '33.33',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_6327cb48d2718',
      'label' => 'Link',
      'name' => 'hero_01_postit_link',
      'type' => 'url',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '33.33',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
    ],
    [
      'key' => 'field_6332395d08a54',
      'label' => 'Primeiro Background da Direita',
      'name' => '',
      'type' => 'message',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'message' => 'Abaixo você deverá colocar informações sobre o primeiro background que fica na direita.',
      'new_lines' => 'wpautop',
      'esc_html' => 0,
    ],
    [
      'key' => 'field_6327d078ffe46',
      'label' => 'Imagem',
      'name' => 'hero_image_02',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '100',
        'class' => '',
        'id' => '',
      ],
      'return_format' => 'url',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ],
    [
      'key' => 'field_6327d083ffe47',
      'label' => 'Post-it',
      'name' => '',
      'type' => 'message',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '100',
        'class' => '',
        'id' => '',
      ],
      'message' => '',
      'new_lines' => 'wpautop',
      'esc_html' => 0,
    ],
    [
      'key' => 'field_6327d086ffe48',
      'label' => 'Título',
      'name' => 'hero_02_postit_title',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '33.33',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_6327d089ffe49',
      'label' => 'Subtítulo',
      'name' => 'hero_02_postit_subtitle',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '33.33',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_6327d08cffe4a',
      'label' => 'Link',
      'name' => 'hero_02_postit_link',
      'type' => 'url',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '33.33',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
    ],
    [
      'key' => 'field_6332395e08a55',
      'label' => 'Segundo Background da Direita',
      'name' => '',
      'type' => 'message',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'message' => 'Abaixo você deverá colocar informações sobre o segundo background que fica na esquerda.',
      'new_lines' => 'wpautop',
      'esc_html' => 0,
    ],
    [
      'key' => 'field_6327d30a59b95',
      'label' => 'Imagem',
      'name' => 'hero_image_03',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '100',
        'class' => '',
        'id' => '',
      ],
      'return_format' => 'url',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ],
    [
      'key' => 'field_6327d30a59b96',
      'label' => 'Post-it',
      'name' => '',
      'type' => 'message',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '100',
        'class' => '',
        'id' => '',
      ],
      'message' => '',
      'new_lines' => 'wpautop',
      'esc_html' => 0,
    ],
    [
      'key' => 'field_6327d30a59b97',
      'label' => 'Título',
      'name' => 'hero_03_postit_title',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '33.33',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_6327d30a59b98',
      'label' => 'Subtítulo',
      'name' => 'hero_03_postit_subtitle',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '33.33',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_6327d30a59b99',
      'label' => 'Link',
      'name' => 'hero_03_postit_link',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '33.33',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_6327d473b8742',
      'label' => 'Sobre',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'placement' => 'top',
      'endpoint' => 0,
    ],
    [
      'key' => 'field_6327d4a4b8744',
      'label' => 'Título',
      'name' => 'about_header_title',
      'type' => 'text',
      'instructions' => 'Neste campo você deverá colocar o título da seção "sobre".',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '100',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_6327d483b8743',
      'label' => 'Conteúdos',
      'name' => '',
      'type' => 'message',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'message' => '',
      'new_lines' => 'wpautop',
      'esc_html' => 0,
    ],
    [
      'key' => 'field_6327d509b8746',
      'label' => 'Conteúdo - Esquerda',
      'name' => '',
      'type' => 'message',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '100',
        'class' => '',
        'id' => '',
      ],
      'message' => 'Abaixo deste campo você deverá colocar as informações sobre o conteúdo que fica na esquerda.',
      'new_lines' => 'wpautop',
      'esc_html' => 0,
    ],
    [
      'key' => 'field_6327d532b8748',
      'label' => 'Título',
      'name' => 'about_content_01_title',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '100',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_63324a78f7bc2',
      'label' => 'Subtítulo',
      'name' => '',
      'type' => 'message',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '100',
        'class' => '',
        'id' => '',
      ],
      'message' => 'Os campos abaixo é responsável apenas pelo subtítulo, os campos onde tem detalhe é onde o texto ficará mais escuro. Caso não queira com detalhes, basta passar o conteúdo no campo abaixo chamado "subtítulo".',
      'new_lines' => 'wpautop',
      'esc_html' => 0,
    ],
    [
      'key' => 'field_6327d54fb8749',
      'label' => 'Subtítulo',
      'name' => 'about_content_01_subtitle',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '25',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_633249dbf7bbd',
      'label' => 'Detalhe do meio da frase',
      'name' => 'about_content_01_subtitle_details_mid',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '25',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_63324adb7c514',
      'label' => 'Continuação',
      'name' => 'about_content_01_subtitle_continue',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '25',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_63324a12f7bbf',
      'label' => 'Detalhe do fim da frase',
      'name' => 'about_content_01_subtitle_details_end',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '25',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_6327d568b874a',
      'label' => 'Imagem',
      'name' => 'about_content_01_image',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '100',
        'class' => '',
        'id' => '',
      ],
      'return_format' => 'url',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ],
    [
      'key' => 'field_6327d520b8747',
      'label' => 'Conteúdo - Direita',
      'name' => '',
      'type' => 'message',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '100',
        'class' => '',
        'id' => '',
      ],
      'message' => 'Abaixo deste campo você deverá colocar as informações sobre o conteúdo que fica na direita.',
      'new_lines' => 'wpautop',
      'esc_html' => 0,
    ],
    [
      'key' => 'field_6327d5c68d546',
      'label' => 'Título',
      'name' => 'about_content_02_title',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '100',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_63324a44f7bc1',
      'label' => 'Subtítulo',
      'name' => '',
      'type' => 'message',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '100',
        'class' => '',
        'id' => '',
      ],
      'message' => 'Os campos abaixo é responsável apenas pelo subtítulo, os campos onde tem detalhe é onde o texto ficará mais escuro. Caso não queira com detalhes, basta passar o conteúdo no campo abaixo chamado "subtítulo".',
      'new_lines' => 'wpautop',
      'esc_html' => 0,
    ],
    [
      'key' => 'field_6327d5c88d547',
      'label' => 'Subtítulo',
      'name' => 'about_content_02_subtitle',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '25',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_63324a04f7bbe',
      'label' => 'Detalhe do meio da frase',
      'name' => 'about_content_02_subtitle_details_mid',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '25',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_63324b077c515',
      'label' => 'Continuação',
      'name' => 'about_content_02_subtitle_continue',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '25',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_63324a30f7bc0',
      'label' => 'Detalhe do fim da frase',
      'name' => 'about_content_02_subtitle_details_end',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '25',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_63323b52058b5',
      'label' => 'Imagem',
      'name' => 'about_content_02_image',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '100',
        'class' => '',
        'id' => '',
      ],
      'return_format' => 'url',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ],
    [
      'key' => 'field_6327d60fea7ca',
      'label' => 'Formulário',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'placement' => 'top',
      'endpoint' => 0,
    ],
    [
      'key' => 'field_63323ad8580e2',
      'label' => 'Shortcode',
      'name' => 'shortcode',
      'type' => 'text',
      'instructions' => 'Aqui você deve digitar o shortcode do formulário.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_6327d63eea7cb',
      'label' => 'Conteúdo acima dos campos',
      'name' => '',
      'type' => 'message',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '100',
        'class' => '',
        'id' => '',
      ],
      'message' => 'Este campo é responsável pelo conteúdo que fica acima dos campos de "curso" e "email" do formulário.',
      'new_lines' => 'wpautop',
      'esc_html' => 0,
    ],
    [
      'key' => 'field_6327d663ea7cc',
      'label' => 'Título',
      'name' => 'form_title',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '50',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_6327d675ea7cd',
      'label' => 'Subtítulo',
      'name' => 'form_subtitle',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '50',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_6327d71bc7c28',
      'label' => 'Faq',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'placement' => 'top',
      'endpoint' => 0,
    ],
    [
      'key' => 'field_6327d72fc7c29',
      'label' => 'E-mail de Contato',
      'name' => 'email_contact',
      'type' => 'text',
      'instructions' => 'Aqui você deverá colocar o e-mail para contato.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '100',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'tab_ancora_topo',
      'label' => 'Âncora do topo',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'placement' => 'top',
      'endpoint' => 0,
      'default_value' => [1, 2, 3, 4],
    ],
    [
      'key' => 'ancora_topo',
      'label' => 'Âncora do topo',
      'name' => 'ancora_topo',
      'type' => 'repeater',
      'instructions' => 'Este campo é responsável pelos links com imagem horizontal no topo do catálogo',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '100',
        'class' => '',
        'id' => '',
      ],
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'block',
      'button_label' => 'Adicionar Bloco',
      'sub_fields' => [
        [
          'key' => 'ancora_topo_title',
          'label' => 'Título',
          'name' => 'ancora_topo_title',
          'type' => 'text',
          'instructions' => 'Neste campo você deverá escolher os cursos que fazem parte de cada série.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '50',
            'class' => '',
            'id' => '',
          ],
          'post_type' => [
            0 => 'product',
          ],
          'taxonomy' => '',
          'allow_null' => 0,
          'multiple' => 1,
          'return_format' => 'object',
          'ui' => 1,
        ],
        [
          'key' => 'ancora_topo_link_bloco_series',
          'label' => 'Link para bloco de série',
          'name' => 'ancora_topo_link_bloco_series',
          'type' => 'number',
          'instructions' => 'Neste campo você deverá escolher para qual bloco de série irá linkar (1º, 2º, 3º, etc)',
          'prepend' => 'Bloco Nº:',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '25',
            'class' => '',
            'id' => '',
          ],
          'post_type' => [
            0 => 'product',
          ],
          'taxonomy' => '',
          'allow_null' => 0,
          'multiple' => 1,
          'return_format' => 'object',
          'ui' => 1,
        ],
        [
          'key' => 'ancora_topo_image',
          'label' => 'Imagem',
          'name' => 'ancora_topo_image',
          'type' => 'image',
          'instructions' => 'Neste campo você deverá escolher a imagem.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '25',
            'class' => '',
            'id' => '',
          ],
          'post_type' => [
            0 => 'product',
          ],
          'taxonomy' => '',
          'allow_null' => 0,
          'multiple' => 1,
          'return_format' => 'object',
          'ui' => 1,
        ],
        [
          'key' => 'ancora_topo_text',
          'label' => 'Texto',
          'name' => 'ancora_topo_text',
          'type' => 'wysiwyg',
          'instructions' => 'Neste campo você deverá escolher os cursos que fazem parte de cada série.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '100',
            'class' => '',
            'id' => '',
          ],
          'post_type' => [
            0 => 'product',
          ],
          'taxonomy' => '',
          'allow_null' => 0,
          'multiple' => 1,
          'return_format' => 'object',
          'ui' => 1,
        ],
      ],
    ],
    [
      'key' => 'field_632cc055f887c',
      'label' => 'Bloco de Séries',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'placement' => 'top',
      'endpoint' => 0,
    ],
    [
      'key' => 'field_632cc090f887e',
      'label' => 'Bloco',
      'name' => 'series_bloco',
      'type' => 'repeater',
      'instructions' => 'Este campo é responsável pelo conteúdo de cada série.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '100',
        'class' => '',
        'id' => '',
      ],
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'block',
      'button_label' => 'Adicionar Bloco',
      'sub_fields' => [
        [
          'key' => 'field_632cc716212ab',
          'label' => 'Cor Principal',
          'name' => 'color',
          'type' => 'color_picker',
          'instructions' => 'Neste campo você deverá escolher a cor principal da série, cor que ficará no fundo e nos botões "ver mais". (em hexadecimal]',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '100',
            'class' => '',
            'id' => '',
          ],
          'default_value' => '#fff',
        ],
        [
          'key' => 'field_632d280e544ff',
          'label' => 'detalhe do título em negrito no começo da frase',
          'name' => 'title_details_first',
          'type' => 'text',
          'instructions' => 'Nesse campo você pode optar por deixar o começo do texto em negrito. Caso queira deixar o título todo em negrito, retire o conteúdo dos campos ao lado.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '33.33',
            'class' => '',
            'id' => '',
          ],
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ],
        [
          'key' => 'field_632cc0f8f8881',
          'label' => 'titulo',
          'name' => 'title',
          'type' => 'text',
          'instructions' => 'Neste campo você deverá digitar o título de cada série.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '33.33',
            'class' => '',
            'id' => '',
          ],
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ],
        [
          'key' => 'field_632cddcc1e81f',
          'label' => 'detalhe do título em negrito no fim da frase',
          'name' => 'title_details_last',
          'type' => 'text',
          'instructions' => 'Nesse campo você pode optar por deixar o final do texto em negrito.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '33.33',
            'class' => '',
            'id' => '',
          ],
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ],
        [
          'key' => 'field_632cc0fef8882',
          'label' => 'subtitulo',
          'name' => 'subtitle',
          'type' => 'text',
          'instructions' => 'Neste campo você deverá digitar o título do conteúdo de cada série.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '100',
            'class' => '',
            'id' => '',
          ],
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ],
        [
          'key' => 'field_632cc12cf8884',
          'label' => 'Cursos',
          'name' => 'posts',
          'type' => 'post_object',
          'instructions' => 'Neste campo você deverá escolher os cursos que fazem parte de cada série.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '100',
            'class' => '',
            'id' => '',
          ],
          'post_type' => [
            0 => 'product',
          ],
          'taxonomy' => '',
          'allow_null' => 0,
          'multiple' => 1,
          'return_format' => 'object',
          'ui' => 1,
        ],
      ],
    ],
    [
      'key' => 'field_632f4575a06f0',
      'label' => 'Lista de Categorias',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'placement' => 'top',
      'endpoint' => 0,
    ],
    [
      'key' => 'field_632f446a0be2d',
      'label' => 'Categorias',
      'name' => 'products_categories',
      'type' => 'taxonomy',
      'instructions' => 'Neste campo você deverá escolher as categorias das séries que deseja.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'taxonomy' => 'product_cat',
      'field_type' => 'checkbox',
      'add_term' => 1,
      'save_terms' => 0,
      'load_terms' => 0,
      'return_format' => 'id',
      'multiple' => 0,
      'allow_null' => 0,
    ],
  ],
  'location' => [
    [
      [
        'param' => 'page_template',
        'operator' => '==',
        'value' => 'page-catalogo.php',
      ],
    ],
  ],
  'menu_order' => 0,
  'position' => 'acf_after_title',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => true,
  'description' => '',
]);